backend:
  name: git-gateway
  branch: master

media_folder: "src/images"
public_folder: "/images"

# run "npx decap-server" for local backend
local_backend: true
# publish_mode: editorial_workflow

collections:
  - label: Pages
    name: pages
    editor:
      preview: false
    files:
      - label: Home
        name: home
        file: "src/_data/pages/home.yaml"
        fields:
          - { name: hero_slogan, label: Slogan, widget: string }
          - { name: hero_desc, label: Slogan Message, widget: string }
          - { name: hero_image, label: Hero Image, widget: image }
          - { name: about_image, label: About Image, widget: image }
      - label: About
        name: about
        file: "src/_data/pages/about.yaml"
        fields:
          - { name: main, label: About Intro, widget: markdown, minimal: true }
          - { name: secondary, label: About Secondary, widget: markdown, minimal: true }
          - { name: terciary, label: About Terciary, widget: markdown, minimal: true }
          - { name: image1, label: Image 1, widget: image, hint: Side-by-side with Image 2 }
          - { name: image2, label: Image 2, widget: image, hint: Side-by-side with Image 1 }
          - { name: image3, label: Image 3, widget: image }
  - label: "Artwork"
    name: "artwork"
    editor:
      preview: false
    files:
      - label: "Samples"
        name: "samples"
        file: "src/_data/samples.yaml"
        fields:
          - label: Sample Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Description, name: desc, widget: string }
              - { label: Image, name: image, widget: image }
              - { label: Spotlight, name: highlight, widget: boolean, default: false, hint: Toggle to show or hide in the Home page. Ideally there should only be 2 or 3 Spotlighted samples. }
              - label: Audio
                name: audio
                widget: file
                media_folder: "/src/audio"
                public_folder: "/audio"
                media_library:
                  name: audio
                  config:
                    multiple: false
              - { label: Price, name: price, widget: number }
              - { label: Date, name: date, widget: datetime, date_format: "MM/DD/YYYY", format: "MM/DD/YYYY" }
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Website
        name: website
        file: "src/_data/global.yaml"
        fields:
          - { name: website_name, label: Website name, widget: string, hint: This name will appear in the browser tab and in search results. }
          - { name: website_desc, label: Website description, widget: string, hint: This description will appear in search results. This should include relevant words you think your users will search for. }
          - { name: website_keywords, label: Website keywords, widget: string, hint: This improves your SEO or search ranking. Include comma-separated words and phrases that you think users will type when searching for your website. }
          - { name: website_logo, label: Website logo, widget: image, hint: The logo must be named "logo.png" }
          - name: socials
            label: Socials
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { name: name, label: Social, widget: string, hint: Please do not change this name }
              - { name: url, label: Social URL, widget: string, required: false }
              - { name: isActive, label: Display, widget: boolean, hint: Toggle to display or hide on the website }
      - label: Navigation
        name: navigation
        file: "src/_data/nav_items.yaml"
        fields:
          - label: Navigation Items
            name: items
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { name: name, label: Name, widget: string }
              - { name: url, label: URL fragment, widget: string, hint: This should always start with a forward-slash "/". }
              - { name: cta, label: CTA, widget: boolean, default: false, hint: "When turned On, this link will be the highlighted link in the navigation bar and in the Home page's hero section. There should only be 1 CTA (Call to Action) link On at a time." }
      - name: newsletter
        label: Newsletter
        file: "src/_data/newsletter.yaml"
        fields:
          - { name: newsletter_desc, label: Newsletter message, widget: string }
          - { name: isDisplayEverywhere, label: Show newsletter widget on all pages?, widget: boolean }